name: ENV variables
on: push
env:
  WF_ENV: Variables available for all the workflow
  SEBA_SECRET: ${{ secrets.SEBA_SECRET }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} #Secret que existe por defecto sin crearlo 


jobs:
  Log-custom-envioronment-variables:
    runs-on: ubuntu-latest
    env:
      JOB_ENV: Variable available only for this job
    steps:
      - name: Log ENV variables - Test 1
        env:
          STEP_ENV: Variable available only for this step
        run: |
          echo "WF_ENV: ${WF_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"
          echo "STEP_ENV: ${STEP_ENV}"
          echo "SEBA_SECRET: ${SEBA_SECRET}"
          echo "GITHUB_TOKEN: ${GITHUB_TOKEN}"
      - name: Log ENV variables - Test 2
        run: |
          echo "WF_ENV: ${WF_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"
          echo "STEP_ENV: ${STEP_ENV}"    

  Log-default-Github-envioronment-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Default environment variables from GitHub  
        run: |
          echo "GITHUB_ACTION: ${GITHUB_ACTION}"
          echo "GITHUB_ACTION_PATH: ${GITHUB_ACTION_PATH}"
          echo "GITHUB_ACTION_REPOSITORY: ${GITHUB_ACTION_REPOSITORY}" 
          echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "GITHUB_API_URL: ${GITHUB_API_URL}"
          echo "GITHUB_BASE_REF: ${GITHUB_BASE_REF}"
          echo "GITHUB_ENV: ${GITHUB_ENV}" 
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_EVENT_PATH: ${GITHUB_EVENT_PATH}"
          echo "GITHUB_JOB: ${GITHUB_JOB}"
          echo "GITHUB_HEAD_REF: ${GITHUB_HEAD_REF}"
          echo "GITHUB_REPOSITORY_OWNER: ${GITHUB_REPOSITORY_OWNER}" 
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"          
  
